[package]
name = "even_numbers"
version = "0.1.0"
authors = ["NoSpooksAllowed <hersgori4@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
